SRGSSR/pillarbox-web

.eslintrc
.husky/pre-commit
package-lock.json
package.json
src/pillarbox.js

This PR adds `eslint` for code style consistency and quality and will be executed at each `pre-commit`.
- add `eslint` dev dependency
- add `eslint-plugin-jest` dev dependency
- add `.eslintrc` configuration file
- add script `eslint` to run the linter
- add husky `pre-commit` to run the linter before each commit
- fix code style on `pillarbox`

chore(eslint): add javascript linter

---

.releaserc

This PR adds the configuration for using the `semantic-release` package, which uses the commit format to automatically generate the version number, automatically produce release notes and finally publish the npm package.
- add distribution branches
- The `github-ci` branch twists the use of semantic release. The reason is to be able to deliver as many pre-releases as possible and create releases by promoting a `pre-release` to a `release` from the `release notes` generated by github.
- add commit analyzer
- add release note
- add change log

chore(semantic-release): add configuration

---

.github/workflows/pre-release.yml
.github/workflows/release.yml
package.json

This PR automates the library delivery while ensuring that unit tests and linter tests pass beforehand.
- add github registry in `package.json` file
- add `pre-release` action
- create change log
- publish npm package to github registry
- create github release note
- add `release` action
- promote a pre-release to a release

chore(github-actions): add pre-release and release configuration

---

.github/workflows/coverage.yml

Adds code `coverage` to `pull-requests`, in order to add it to Github `status checks`.
- add `coverage` workflow

chore(github-actions): add code coverage

---

.github/workflows/coverage.yml
.github/workflows/github-page.yml
package.json

Adds the `github-page` workflow to generate the github page.
- add `parcel` build `targets` to the package.json
- add npm script to build the github page
- modify `build` script to point to build target `main`
- add `github-page` workflow
- update indentation in `coverage` workflow

chore(github-action): add github page

---

.github/workflows/quality.yml
.husky/pre-commit
.stylelintrc
demo/scss/index.scss
package-lock.json
package.json

Adds a css linter to ensure consistency throughout the project and force the use of rational-order.
- add `stylelint`, `stylelint-config-rational-order`, `stylelint-order` dev dependencies
- add `.stylintrc` configuration file
- add stylelint npm `script` to validate css files
- add stylelint to husky's `pre-commit` hook
- add stylelint to github action `quality`
- update css to comply with linter rules

chore(stylelint): add css linter

---

.gitignore
jest.config.js
package-lock.json
package.json

Adds `jsdom` to test DOM manipulations with `jest`.
- add `jest-environment-jsdom` dev dependency
- add `jest.config.js` configuration file
- add `coverage` folder to `.gitignore`

chore(jest): add jsdom environment

---

.eslintrc
package-lock.json
package.json
test/pillarbox.spec.js

Adds a test case to ensure that when the `player` is created, the instance is a component of type `Player`.
- adds a test case for `player` initialization
- adds `types/jest` to dev dependencies to add autocompletion
- adapts `linter` rules for Jest

test(pillarbox): player initialization

---

demo/src/index.js
package-lock.json
package.json
src/middleware/srgssr.js
src/pillarbox.js
src/utils/Drm.js
test/middleware/srgssr.spec.js
test/pillarbox.spec.js
test/utils/Drm.spec.js

Resolves #27 and allows DRM-protected content to be played in any DRM-supported environment from a URN or single source.
- add `videojs-contrib-eme` to `npm` dependencies
- add `eme` plugin to `pillarbox` and expose its `version`
- add `Drm` class for creating `keysystems` objects and identifying whether a `resource` contains drm
- update `SrgSsr` to handle DRM resources and some refactoring
- update the demo
- update to video.js [8.5.2](https://github.com/videojs/video.js/releases/tag/v8.5.2)

feat: drm content playback

---

demo/src/index.js
package.json
src/dataProvider/services/DataProviderService.js
src/middleware/srgssr.js
src/utils/AkamaiTokenService.js
test/__mocks__/streamTypeList.js
test/middleware/srgssr.spec.js
test/utils/AkamaiTokenService.spec.js

Resolves #28 and allows content protected by an Akamai token to be played.
- add `AkamaiTokenService` to hangle token generation
- update `SrgSsr` to handle token-protected resources
- update the demo
- update package.json `version`

feat: token-protected content playback

---

src/components/player.js
src/pillarbox.js
src/typedefs.js
test/components/player.spec.js

Resolves #38 by adding the `audioTrack` function to simplify audio track retrieval and selection. This function allows to:
- retrieve the currently active audio track
- activate an audio track based on `language` and `kind` properties
Also, when selecting an audio track, if the `kind` property is not satisfied, the first audio track satisfying the `language` condition will be returned, or `undefined` if no condition is satisfied.
```javascript
// Get the current audio track
player.audioTrack();
// Activate an audio track
player.audioTrack({language:'en', kind:'alternative'})
```
- redefine default video.js `player` component
- add `audioTrack` function
- add a `typedefs` file to keep all types
- add `trackSelector` type representing the track to be selected

feat(player): simplifies audio track handling

---

package-lock.json
package.json

This PR update video.js to version [8.6.1](https://github.com/videojs/video.js/releases/tag/v8.6.1) 
- update package.json file

chore(npm): update video.js to v8.6.1

---

src/pillarbox.js

In the `VERSION` property, when `parceljs` performs minification the plugin name is changed to a random value.
- set the `eme` key manually instead of using `videojs.getPlugin('eme').name`

fix(pillarbox): eme plugin name does not survive minification

---

src/components/player.js
test/components/player.spec.js

When changing the audio track, if the parameter passed to the `audioTrack` function does not match to any audio track, the audio track already enabled is disabled.
- update audio track activation condition
- add documentation links
- update test case

fix(player): audio track disabled if no selection criteria met

---

src/middleware/srgssr.js
src/pillarbox.js
test/middleware/srgssr.spec.js

Resolves #39 by adding support for blocking reasons to prevent content from being played.
- add error messages for blocking reasons in `pillarbox`
- add logic to `setSource` to display an `error` if content has a `blockingReason`

feat(srgssr-middleware): add support for SRG SSR blocking reasons

---

.terserrc
build.js
package-lock.json
package.json

Resolves #42 and allows to compile the project in order be able to generate
a tarball to be used as an npm dependency. Compilation will produce the following files :
- `pillarbox.css`, at this stage contains only the default styles for video.js
- `pillarbox.js`, offers the SRG SSR experience
- `pillarbox.core.js`, contains only video.js enhancements
Tarball generation is not part of this PR as it is already configured to be
generated by `semantic-release`.
- update `package.json` file
- add `files` that will be included in the package
- add parcel compilation `targets`
- add build `scripts` for js and css
- add `terserrc` to remove comments from builds
- add `rimraf` dev dependency
- add `build.js` file which will contain the various dependencies to be exposed

chore(npm): generate npm pack friendly compiled files

---

package.json

This avoids publishing the github page in the `github-page` subdirectory instead of the `root`.
- add `distDir` file for target `github-page`

chore(npm): github page destination folder

---

src/analytics/SRGAnalytics.js

Fixes #60 where `media_position` is not updated after resuming playback after `seeking` while the player was `paused`.
- ensure the time is up to date before calling `notify` play

fix(srg-analytics): playhead position is not updated

---

.gitignore
demo/index.html
demo/scss/dialog.scss
demo/scss/examples.scss
demo/scss/index.scss
demo/src/ExampleDialog.js
demo/src/Examples.js
demo/src/ExamplesLoader.js
demo/src/index.js

Resolves #51
A demo page with several functionalities :
* An input box allowing url and srg/ssr urn loading.
* A list of examples.
* Responsive design.
* Selected items are loaded into a modal with pillarbox-web.
Removed old demo page.

feat(demo): Add a demo page with example

---

demo/src/ExampleDialog.js
demo/src/Examples.js

Closes #64
Modified examples with license URLs to adhere to the expected video-js format of 'keySystems', specifying the vendor and URL as such :
```javascript
{
'title': '...',
'src': ' ...',
'keySystems': {
'com.widevine.alpha': '...'
}
}
```

feat(demo): add DRM support to demo page

---

src/dataProvider/model/MediaComposition.js

Even though the `blockReason` feature has been implemented. It seems that the `blockReason` property has been forgotten, resulting in blocking reasons appearing as simple error messages.
- adds the `blockReason` property to the `getMainResources` function

fix(media-composition): missing block reason property

---

demo/src/index.js

This configuration allows:
- set the threshold for displaying the the progress bar. This avoids displaying the
progress bar when a live stream has too short a
live window.
- set the tolerance at which the playback position is considered live.
- adds the `liveTracker` configuration

chore(demo): add live tracker configuration

---

demo/scss/examples.scss

This allows the category title to remain at the top of the page when scrolling down.
- adds the same background color as the body
- removes the title margin
- adds padding at top and bottom

chore(demo): add position sticky to category's title

---

demo/src/ExampleDialog.js

Allows to close the `dialog` by clicking on the backdrop.
- add a click event listener which will `close` the `dialog` element only if the `target` element is the `dialog` itself

chore(demo): close dialog element

---

demo/scss/examples.scss
demo/src/example/example-page.js

This pull request allows us to enhance the presentation of examples, which include a title and a description.
> A picture is worth a thousand words
| Current display | Improved display |
| --------- | --------- | 
| ![current](https://github.com/SRGSSR/pillarbox-web/assets/3347810/8e4c5f0f-aaa5-44e7-8538-563363812e2f) | ![improved](https://github.com/SRGSSR/pillarbox-web/assets/3347810/e57ca8d8-fb16-4260-b1d6-be45b8a71977) | 
- A CSS class `example-title` has been added to manage the style of an example title.
- A CSS class `example-description` has been added to manage the style of an example description.
- The example cell has been updated when it contains both a title and a description.

feat(demo): improve examples layout display

---

demo/scss/index.scss
demo/scss/spinner.scss
demo/src/content-lists/content-tree-page.js
demo/src/core/il-provider.js
demo/src/core/spinner-component.js
demo/src/search/search-page.js

Closes #82
Introduces a `SpinnerComponent` that can be dynamically attached to a DOM element and can be shown or hide on command.
This spinner offers a visual cue to signify that content is being loaded or processed during user interactions or asynchronous operations. It has been added to the following pages :
- **Search** : The spinner is shown whenever a search is launched.
- **Lists**: The spinner is shown when a section is opened.
- The search page is now a class.
- Performing a new search will abort the previous request if it's ongoing.

feat(demo): add spinner component

---

demo/src/player/player.js

Temporarily exposes `videojs` in the object `window` to allow Comscore to initialize correctly.
- add a global variable named `videojs` extending `pillarbox`

chore(demo): expose videojs in window object

---

demo/scss/index.scss
demo/scss/search.scss
demo/scss/sentinel.scss
demo/src/core/html-utils.js
demo/src/core/il-provider.js
demo/src/core/sentinel-component.js
demo/src/core/spinner-component.js
demo/src/index.js
demo/src/lists/lists-page.js
demo/src/lists/lists-sections.js
demo/src/search/search-page.js

Added pagination by providing continuous loading of results without the need for explicit actions:
- Introduced a new `SentinelComponent` that utilizes the Intersection Observer API to trigger the loading of the next page of search results when it comes into view.
- The `SearchPage` integrates the new `SentinelComponent` and adds  a `nextPage` method to fetch and display the next set of search results.
Renamed the following file:
- `content-tree-page.js` to `lists-page.js`.
- `content-tree-root-sections.js` to `lists-sections.js`.

feat(demo): add content pagination

---

package-lock.json

Running the command `npm outdated` returns the following result:
| Package                            | Current | Latest  |
|------------------------------------|---------|---------|
| @babel/core                        | 7.23.2  | 7.23.3  |
| @babel/preset-env                  | 7.23.2  | 7.23.3  |
| @commitlint/cli                    | 18.0.0  | 18.4.3  |
| @commitlint/config-conventional    | 18.0.0  | 18.4.3  |
| @parcel/transformer-inline-string  | 2.10.0  | 2.10.3  |
| @parcel/transformer-sass           | 2.10.0  | 2.10.3  |
| @semantic-release/github           | 9.2.1   | 9.2.3   |
| @semantic-release/npm              | 11.0.0  | 11.0.1  |
| @types/jest                        | 29.5.6  | 29.5.10 |
| eslint                             | 8.52.0  | 8.54.0  |
| eslint-plugin-jest …

chore(npm): update dev dependencies

---

src/dataProvider/services/DataProvider.js

When a chapter's URN is loaded, the entire media is played instead of just the requested chapter.
This fix allows a chapter to be played outside the context of the media it belongs to.
Additionally, setting the `onlyChapters` parameter to `true` ensures compliance with the initial decision and follows the same behavior as Pillarbox Android and iOS.
- change the default value of the `onlyChapters` parameter
- update the `jsdoc` associated with the parameter

fix(data-provider): onlyChapters parameter default value

---

demo/404.html
demo/index.html

Integrated the [spa-github-pages](https://github.com/rafgraph/spa-github-pages) guide. The following steps were followed:
1. Copied the `404.html` file from the guide and added it to the repository without modifications.
2. Added the redirect script from the guide's `index.html` to the project's `index.html` file.
These changes make the GitHub page URLs shareable.

feat(demo): make github page urls shareable

---

package.json

- Added 'demo/404.html' to the github pages sources.

fix(demo): add 404 page in github page target

---

demo/src/player/player-dialog.js

Ensures that the player has been reset before loading new media. This prevents the old media being displayed for a fraction of the time before the new media is loaded. It also allows media without a poster to inherit the poster from the previous media.
[Screencast from 30. 11. 23 16:29:58.webm](https://github.com/SRGSSR/pillarbox-web/assets/34163393/0e87bc5e-38dc-4ed3-b39d-02f074170b38)
- reset player
- reset error screen
- reset title bar

chore(demo): reset player state before loading new media

---

demo/src/player/player-dialog.js
package-lock.json
package.json

Removes the temporary code that resets the player's UI between two source loads. This was made possible with the release of
[video.js@8.7.0](https://github.com/videojs/video.js/releases/tag/v8.7.0).
- removes temporary code
- updates the video.js dependency

chore(demo): remove temporary code resetting the player's UI

---

demo/scss/content-tree.scss
demo/src/core/router.js
demo/src/core/string-utils.js
demo/src/index.js
demo/src/lists/lists-page-state-manager.js
demo/src/lists/lists-page.js

Closes #109
Query parameters have been added to the URL whenever a section is opened on the lists page, making it navigable through the browser history stack. Examples of decoded urls :
```text
/lists?section=tv-topics&bu=rts&nodes=urn:rts:topic:tv:665
/lists?section=radio-shows&bu=rts&nodes=a9e7621504c6959e35c3ecbe7f6bed0446cdf8da,urn:rts:show:radio:9801398
```
Refactor the state management of the lists page to introduce the `ListsPageStateManager` class. This class facilitates navigation and retrieval of section data.

feat(demo): lists page state management

---

demo/src/lists/lists-page-state-manager.js

Fixes a bug in the params generation algorithm, `toLowerCase` was applied to the setion not the bu as intended.

fix(demo): removed 'toLowerCase' from section

---

demo/scss/search.scss
demo/src/search/search-page.js

Closes #126
Enhance the feedback for the empty search results page in the demo:
- Displays "Enter Something to search" instead of "No results" when the results container is empty.
- When a search is performed and there are no results, the icon changes and the text "No results" is displayed.

chore(demo): improve visual feedback on empty results

---

src/middleware/srgssr.js
test/middleware/srgssr.spec.js

The Akamai token was generated for all URNs, regardless of whether or not they were protected by an Akamai token.
This was due to the fact that the `return` statement was missing from the condition used to check whether or not a resource was protected by an Akamai token.
- add missing `return` statement to the `composeAkamaiResources` function
- add a test case checking that the token is not generated if the resource doesn't require it

fix(srgssr-middleware): akamai token generation

---

.github/workflows/download-crowding.yml
.github/workflows/upload-crowding.yml

Resolves #70 by adding two GitHub actions for downloading and uploading translations to Crowdin.
- `upload_crowdin.yml`, sends translation files to Crowdin only if `src/lang/**` folder has been modified
- `download_crowdin.yml`, downloads translation files from Crowdin `every 12 hours` and creates a pull request to main if translations have been modified

chore(github-actions): add Crowdin workflows

---

demo/scss/index.scss

Defines a minimum height for all buttons to ensure visual consistency.
- center button content and set minimum height

chore(demo): button min height

---

demo/src/player/player-dialog.js
demo/src/player/player.js
docs/KNOWN_ISSUES.md

Closes #113
Calling `player.reset()` before loading a new source was preventing the `webkitneedkey` event
from being listened by `videojs-contrib-eme` resulting in the inability to play DRM protected content.
This commit creates a new player everytime the modal is open in the demo and disposes the player
when closing the modal. Additionally it adds a `KNOWN_ISSUES` document describing the problem with
`player.reset()` and how to mitigate it during the integration of Pillarbox for tracking purposes.

fix(demo): dispose the player after closing the modal 

---

demo/scss/player.scss

When navigating with the keyboard, the focus is not correctly set on the `select` html elements of the captions settings.
This is caused by two css rules in two different files:
1. **player.scss**, `select` set to `all:unset`
2. **index.scss**, `select` set to `outline:none`
- Set `outline` to `solid` during `focus-within`. This solution was preferred while waiting for the end of the transition to Lit.

chore(demo): player captions settings focus

---

demo/src/core/toggle-switch-component.js
demo/src/core/toggle-switch-component.scss
demo/src/index.js
demo/src/layout/header-component.js
demo/src/player/player.js
demo/src/router/route-link-component.js
demo/src/router/router.js
demo/src/search/search-bar-component.js
demo/src/search/search-page.js
demo/src/settings/preferences-provider.js
demo/src/settings/settings-page.js
demo/src/settings/settings-page.scss

Closes #114
Implemented a settings page for the demo. The following features were introduced:
- **Toggle-switch Web Component:** A `toggle-switch web component, mirroring the design of an Apple settings toggle.
- **Settings Page:** Added a settings page that allows users to toggle the following settings:
- **Autoplay:** The player in the demo page will autoplay when opened (default: false).
- **Muted:** The player will launch muted (default: true).
- **Debug Mode:** The player operates in debug mode, and logs can be viewed in the browser's console (default: false).
ll settings are stored in the local storage, ensuring that the demo page remembers user preferences across sessions.
When the debug mode is enabled, a query parameter "debug" is appended to the URL.

feat(demo): settings page

---

demo/src/player/player-dialog.js

Modifies the behavior of the dialog in the demo by preventing background from being scrollable when the dialog is open. 
Forces the `overflow-y` style of the `document.documentElement` to be `hidden` when the dialog is opened, and restores it to `scroll` when the dialog is closed.

chore(demo): remove scrolling when the dialog is open

---

package-lock.json
package.json

This update to video.js introduces a new parameter for enabling smooth seeking via player options.
```javascript
// Enables the smooth seeking
const player = videojs('player', {enableSmoothSeeking: true});
// Disable the smooth seeking
player.options({enableSmoothSeeking: false});
```
- update `package.json`

chore(npm): update to video.js version 8.9.0

---

demo/src/player/player-dialog.js
demo/src/search/search-page.js

Closes #134 
Modified the player dialog to listen for changes in the router, allowing it to open the dialog based on specific query parameters.
This change is integrated with all current pages of the demo.
- When the player dialog is open, query parameters are updated to reflect the "src", "type" and "keySystems" that are used to initialize the player content.
- Upon closing the dialog, these query parameters are deleted from the url, other parameters are preserved.
- The "keySystems" parameter is flattened into three separate parameters: "vendor", "licenseUrl", and "certificateUrl."

feat(demo): Open Player from Query Params

---

demo/src/player/player.js
src/pillarbox.js
test/pillarbox.spec.js

Closes #155 by enabling smooth seeking by default for Pillarbox. This feature improves the user experience by providing smoother interaction with the progress bar.
[Screencast from 03. 01. 24 15:21:49.webm](https://github.com/SRGSSR/pillarbox-web/assets/34163393/53d1e3f3-4530-401b-a2c9-732945b0e2ce)
- **Pillarbox** `options` `enableSmoothSeeking` property is set to `true`
- add a test case
- **Demo player**, remove the `enableSmoothSeeking` from `DEFAULT_OPTIONS`

feat(pillarbox): enable smooth seeking by default

---

demo/src/core/content-link-component.js
demo/src/core/content-link-component.scss
demo/src/examples/examples-page.js
demo/src/examples/load-media-form-component.js
demo/src/index.js
demo/src/lists/lists-page-state-manager.js
demo/src/lists/lists-page.js
demo/src/player/player-dialog.js
demo/src/router/router.js
demo/src/search/search-page.js
demo/src/search/search-page.scss
demo/src/theme/theme.scss

Closes #149
Closes #150
This change refactors all the content buttons of the demo application into links enabling sharing and further navigation options.
- Created a `ContentLinkComponent` that implements a link within the application with the look of the previous buttons but replaces them for links.
- Refactored all buttons on the "Examples," "Search," and "Lists" pages of the demo application to use the newly created component.
- Corrected a regression introduced in the application's router regarding the base url.

feat(demo): use links instead of buttons

---

demo/player.html

Closes #157 by adding a test page containing only the player to facilitate development work.
Handles the following query parameters:
- `audioModeOnly`, activates the player bar
- `currentTime`, playback start position
- `debug`, debugging mode
- `ilHost`, IL host
- `language`, player language
- `resize`, makes the player resizable
- `urn`, content to be played

chore: add player test page

---

demo/index.html
demo/src/examples/load-media-form-component.js
demo/src/examples/load-media-form-component.scss
demo/src/theme/animations.scss

Closes #151
- Keyboard navigation is now disabled when the DRM settings form is hidden.
- The close button of the player dialog has been moved to the end providing a more predictable and intuitive interaction.
- A descriptive label has been added to this same close button of the player dialog.

chore(demo): improve accessibility

---

demo/player.html
demo/src/player/player.js
src/pillarbox.js
test/pillarbox.spec.js

Closes #167 by enabling several options by default. These changes enhance the out-of-the-box experience for Pillarbox and improve default functionalities to facilitate a smoother integration process. The options that have been enabled are as follow:
Enabled the Live UI by default, providing the following features:
- A progress bar for seeking within the live window.
- A clickable button to seek to the live edge, accompanied by a circle indicating if the playback is at the live edge.
By default, the threshold for displaying controls within the live window is set to 120 seconds, and live playback is considered within 15 seconds from the seekable end.
Enabled the EME (Encrypted Media Extensions) plugin by default to support DRM integration and ensure compatibility with protected content. …

feat(pillarbox): add default options for pillarbox

---

.editorconfig
docs/KNOWN_ISSUES.md

Introduced a section in the known issues documentation detailing a cross-platform compatible approach for setting the start position of media, addressing a specific issue encountered on iOS Safari.

docs: start position workaround for ios safari

---

demo/scss/index.scss
demo/src/components/code-block/code-block.js
demo/src/components/code-block/code-block.scss
demo/src/components/player/player.js
demo/src/index.js
demo/src/layout/content/examples/load-media-form-component.js
demo/src/layout/content/showcase/showcase-component.js
demo/src/layout/content/showcase/showcase-page.js
demo/src/layout/content/showcase/start-time-showcase.js
demo/src/layout/content/showcase/starttime-example.txt
demo/src/layout/header/header-component.js
demo/src/layout/header/header-component.scss
demo/src/router/route-link-component.js
package-lock.json
package.json

Closes #174
Introduces a new showcase page that displays various demonstrations highlighting the player's capabilities, akin to the existing mobile app showcases:
- Added a showcase on the new page demonstrating how to initiate media playback at a specified start time.
- Added 'highlight.js' for code highlighting purposes.
- Introduced a new web component (`code-block`) that seamlessly integrates with 'highlight.js'.
- Developed a versatile showcase component serving as the foundational building block for all showcases. It includes a description section and an optional implementation section.
- Moved the settings page to the top of the interface, allowing more menu space for improved mobile device usability.
- Updated the icon for DRM settings to differentiate it from the Demo settings …

feat(demo): showcase videos with a specified start time

---

package-lock.json
package.json

This video.js update removes the `X` from the `error-display` and expose the `version` through the player instance.
```javascript
const player = videojs('player');
// Display video.js version
player.version();
```
- update package.json and package-lock.json

chore(npm): update to video.js version 8.10.0

---

.github/workflows/release.yml

Allows to publish a `pre-release` as a `latest` `dist-tag` directly from the GitHub [releases page](https://github.com/SRGSSR/pillarbox-web/releases).
It is also possible to set an old `tag` as `latest` from the GitHub [releases page](https://github.com/SRGSSR/pillarbox-web/releases):
- if the old tag is a `pre-release`, simply promote it to a `release`
- if the old tag had been marked as `release`, it must be marked as `pre-release`, then as `release`, so that the `released` event is triggered again by GitHub actions
- deletes the first character from `ref_name` to keep only the version number

chore(github-actions): publish selected pre-release tag as the latest dist-tag

---

package-lock.json
package.json
src/middleware/srgssr.js
test/middleware/srgssr.spec.js

Video.js in version [8.11.1](https://github.com/videojs/video.js/releases/tag/v8.11.1) offers the possibility of providing more detail when an error occurs. To this end, the `metadata` property, which is an object, has been added. This object also has an `errorType` property, giving more context on the error that has occurred. Finally, the `metadata` object can host any other `custom property`.
Pillarbox has a similar mechanism, except that instead of naming the `metadata` property, it's called `cause` and has a `type` property. The term `cause` has been borrowed directly from the `Error` object, so as not to introduce a new term.
However, to remain consistent with video.js, the term `cause` has been dropped in favor of `metadata`.
- update of srgssr-middleware
- update unit tests
- …

feat(srgssr-middleware): use metadata instead of cause when an error occurs

---

package.json

Adresses a bug that was introduced in #185 by restoring the publicUrl property in the parcel target `github-page` that was dropped.

fix: demo page not working on github

---

src/pillarbox.js
test/pillarbox.spec.js

Resolves #182 by converting the `Pillarbox` class into a function.
This changes enhances the developper experience by providing the same interface that they are used to in video.js,

refactor: use function instead of class

---

package-lock.json
package.json

For more information, please refer to https://github.com/videojs/videojs-contrib-eme/pull/201
- updates the `package.json` file
- updates the `package-lock.json` file

chore(npm): update videojs-contrib-eme to version 3.11.2

---

.github/workflows/github-page.yml
.github/workflows/pre-release.yml
.github/workflows/quality.yml
.github/workflows/release.yml
package-lock.json
package.json

For more information, please refer to https://github.com/semantic-release/semantic-release/releases/tag/v23.0.0
- updates the `package.json` file
- updates the `package-lock.json` file
- updates github actions to use node v20
Refer to https://github.com/SRGSSR/pillarbox-web/issues/181#issuecomment-1926655838

chore(npm): update semantic-release to version 23.0.0

---

docs/README.md
docs/api/index.md
docs/api/tutorials/Supported Media Types.md

Transfers all existing wiki articles to the newly created JSDoc site. This revision consolidates all documentation onto a single platform, enabling association with specific library versions.

docs: move wiki articles to generated jsdoc site

---

docs/README.md
docs/api/index.md
package.json

Addresses several updates to the distribution configuration.
- Removed `browser` field to prioritize `module` imports.
- Added `style` and `types` field to the package.json.
- Updated the output file name in the `"build:css"` script from `video-js.min.css` to `pillarbox.min.css`.
- Updated the quick guide to reflect how to properly integrate the library.
---
These configuration was tested in conjunction with the demo (see SRGSSR/pillarbox-web-demo#7) to ensure that the library is easily integrated as a npm module.

fix: update build and distribution configuration

---

docs/README.md
docs/api/index.md

Updates the quick start guide to offer guidance on how to setup the token for the Github registry. A link has been provided to the official Github documentation on how to generate the token.

docs: update quick start guide

---

package.json
scss/pillarbox.scss
tsconfig.json

Resolves #202 by removing the `.css` suffix from the Video.js import statement in the Pillarbox theme. The Video.js CSS is now correctly bundled with the Pillarbox theme.
Resolves #205 by exporting the `Player` class on the main entry point of the generated typings. This change allows the Pillarbox custom player to be accessible.
- Removed `css` suffix from the Video.js import statement in the Pillarbox theme.
- Generated the typings directly from `build.es.js` instead of `src/**/*`.
- Changed the `package.json` default `types` export to `dist/types/build.es.d.ts`.

fix: typings and css generation

---

src/middleware/srgssr.js
src/pillarbox.js

Considering we generate two builds for the library it makes sense to perform the declaration of SRG SSR specific options in the middleware itself. This approach prevents the `core` build from exposing options specific to the SRG SSR business logic and ensures these options are only present when necessary.
- Moved the declaration of SRG SSR specific options from `src/pillarbox.js` to `src/middleware/srgssr.js`.

refactor(srgssr-middleware): move srgssr specific options declaration

---

.github/workflows/github-page.yml
.github/workflows/preview.yml

Resolves #196 by introducing pull request previews using `rossjrw/pr-preview-action`. This new workflow enables us to review both visual and functional changes before merging.
The preview functionality work in the following manner:
1. **Triggering a Preview**: Whenever a pull request is either opened, re-opened, or updated, the project undergoes a build process. The contents of the `dist` directory are copied under `pr-preview/pr-${github.ref}` located in the `gh-pages` branch.
2. **Cleaning Up**: Once a pull request is closed, the corresponding preview folder (specific to the closed pull request) is deleted.
- The `JamesIves/github-pages-deploy-action` has been updated from version 3 to version 4. This update introduces the following configurations to this action:
- `force: false`: This …

ci: add pull request previews

---

index.html
src/dataProvider/model/MediaComposition.js
src/middleware/srgssr.js
test/dataProvider/model/MediaComposition.spec.js
test/middleware/srgssr.spec.js

This PR adds support for blocked segments, chapters, intervals and remote text tracks.
To allow developers to create their own experience, metadata text tracks are used. This type of text track has the advantage of not being displayed on screen, however, it is possible to listen to cue change events and react to them as required.
Blocked segments are portions of content that must not be played for various reasons, such as legal, geo-blocking, etc. Resolves #211
```javascript
// Accessing raw data
player.currentSource().mediaData.blockedSegments;
// Listen for cuechange events and get the active cue
player.textTracks().getTrackById('srgssr-blocked-segments').on('cuechange', ()=>{
const [active] = Array
.from(player.textTracks().getTrackById('srgssr-blocked-segments').activeCues); …
```

feat: handle chapters, block segments, time intervals, remote text tracks

---

index.html
src/middleware/srgssr.js
test/middleware/srgssr.spec.js

On Safari, regardless of device type, text tracks seem to take longer to build up. As a result, `chapters`, `blocked segments` and `intervals` are not loaded in the `player`.
A workaround has been discussed here: https://github.com/videojs/video.js/issues/8519
This is worth reporting to Apple.
- add a `promise` in `createTextTrack` with a delay of `100ms`
- modify `addChapters`, `addBlockedSegments`, `addIntervals` to support the `promise`
- replace the `json` object with a `VTTCUE` in `addTextTrackCue`
- use standard `activeCues` property in `getBlockedSegment`
- update unit tests
- update development page

fix(srgssr-middleware): text tracks do not load on safari

---

index.html
src/components/player.js
src/pillarbox.js
test/components/player.spec.js
test/pillarbox.spec.js

This pull request addresses 2 issues with the default options:
1. The `eme` plugin is not loaded by default in the following manner:
```javascript
videojs.options.plugins = { eme: true };
```
To address this limitation, this change 
2. Integrators must explicitly set the `fill` option to `true` even though this commonly expected behaviour.
- Modifies the player constructor to automatically set the `eme` plugin option to true, ensuring its activation by default.
- Moved the import of `videojs-contrib-eme` to the player component.
- Activates the fill option by default.

feat: modify default options

---

index.html
src/middleware/srgssr.js
test/middleware/srgssr.spec.js

This new feature allows to listen to events linked to chapters, intervals and blocked segments directly from the player. This eliminates the need to check that text tracks are loaded correctly, in order to avoid errors.
These events will contain a `data` property whose value will be the `VTTCue` when entering the cue or `undefined` when leaving it. This is valid for chapters and intervals, however the exit of a blocked segment is not notified, since it occurs instantaneously.
**Added events:**
- `srgssr/blocked-segment`
- `srgssr/chapter`
- `srgssr/interval`
**Usage:**
```javascript
// Listen to an event
player.on('srgssr/blocked-segment', ({ type, data }) => {
// do something
});
// Listen to multiple events at the same time
player.on([
'srgssr/blocked-segment',
'srgssr/chapter', …
```

feat(srgssr-middleware): add custom text tracks cuechange event proxy

---

docs/api/tutorials/Known Issues.md

Updates the known issues documentation to address the problem of Yarn installing multiple versions of `video.js`, unlike npm. See #222.

docs: update known issues for yarn

---

src/middleware/srgssr.js
test/middleware/srgssr.spec.js

Adds a `tolerance` to prevent some `Safari` browsers from getting stuck at the `endTime` of a blocked segment.
> [!NOTE]
To maintain a certain consistency in the experience, this tolerance is applied to all browsers.
- add a tolerance of 0.1s `handleCurrentTime`
- update the related test case
- adds a missing test case for `srgAnalytics`

fix(srgssr-middleware): safari stalls at end of blocked segment

---

index.html
scss/components/_control-bar.scss

The property `align-items` is not compatible with the value `end` on Safari versions less than 15.4.
Changes the `dvh` unit used in the demo, which is not compatible with older browsers.
- change value of `align-items`
- use `%` instead of `dvh` in the demo page

fix(control-bar): end value in align-items is not compatible with old Safari

---

.releaserc

When Pillarbox is released, the `version` property of `package-lock.json` is not
updated.
As a result, the `version` properties of `package.json` and `package-lock.json` are out of sync.
- updates `.releaserc` to add `package-lock.json` to the `@semantic-release/git` module

chore(npm): add packge lock to semantic release config file

---

src/middleware/srgssr.js

The `??` operator has been removed, as it is not compatible with older browsers. This can be a problem when Pillarbox is used on televisions, for example.
- replace nullish coalescing by a ternary operator

fix(srgssr-middleware): incompatibility of older browsers with nullish coalescing

---

.babelrc
package-lock.json
package.json
rollup.config.js

Resolves #230 by integrating Babel into the rollup configuration to enhance compatibility across older browsers, aligning with the browser range supported by Video.js.
The following tables illustrate the impact on bundle sizes after integrating the transpilation step:
***Minified Size Comparison***
| Destination                  | With Babel | Without Babel |
|------------------------------|------------|---------------|
| `dist/pillarbox-core.es.js`  | 1.37 KB    | 1.37 KB       |
| `dist/pillarbox-core.umd.js` | 654.12 KB  | 653.36 KB     |
| `dist/pillarbox.es.js`       | 55.16 KB   | 52.6 KB       |
| `dist/pillarbox.umd.js`      | 702.12 KB  | 699.28 KB     |
***Gzipped Size Comparison***
| Destination                  | With Babel | Without Babel | …

chore(bundle): add babel transpilation

---

index.html
scss/pillarbox.scss

This feature initializes the player with the default `pillarbox` CSS theme. This saves the developer from having to add `video-js` and then `pillarbox-js` in the CSS classes.
```html
<video class="video-js pillarbox-js" controls>
<video class="pillarbox-js" controls>
```
However, it remains possible for a developer to use the default video.js theme if the use case so requires.
```html
<video class="video-js" controls>
```
- `pillarbox-js` CSS extends `video-js` CSS
- development page remove `video-js` class

feat: add pillarbox-js css as main theme

---

docs/api/tutorials/Options.md
index.html
src/dataProvider/services/DataProvider.js
src/middleware/srgssr.js
test/dataProvider/services/DataProvider.spec.js
test/middleware/srgssr.spec.js

This feature introduces a new option called `dataProviderUrlHandler` to the
`srgOptions` object allowing developpers to create a custom URL handler to
query any back-end and still use SRGSSR functionality, as long as the returned
object conforms to the mediaCompostion.
The `dataProviderUrlHandler` option defines a function that takes an argument
symbolizing a content identifier and returns a string symbolizing the
URL of the back-end to be queried.
> [!TIP]
> How to use the `dataProviderUrlHandler` option
```javascript
const player = pillarbox('player', {
srgOptions: {
// defines the custom URL handler
dataProviderUrlHandler: (id) => `https://my-domain.com/content/${id}`
}
});
// load the src
player.src({src:'my-content-id', type:'srgssr/urn'});
```
> [!CAUTION]
> If the object returned …

feat: add url handler

---

src/components/player.js
test/components/player.spec.js

Adds a `bufferedRanges` function which uses the `buffered` function native to
`HTMLMediaElement` and allows to know the status of the buffering performed by
the browser for a given media.
This function is particularly useful as it can highlight unsolicited gaps in
the media resulting in frame loss.
ref: https://github.com/videojs/http-streaming/issues/1369#issuecomment-1475965185
- add bufferedRanges function to the player

feat(player): add bufferedRanges helper function

---

src/components/player.js
test/components/player.spec.js

Adds a `seekableRanges` function which is particularly useful to get an array of ranges representing the portions of media that the user agent is able to seek to. `seekableRanges` uses the `seekable` function native to `HTMLMediaElement`.
- add seekableRanges function to the player

feat(player): add seekableRanges helper function

---

docs/api/tutorials/Options.md
index.html
src/dataProvider/services/DataProvider.js
src/middleware/srgssr.js
src/middleware/typedef.ts
test/dataProvider/services/DataProvider.spec.js

Resolves #241, by allowing developers to define their own `dataProvider` and thus avoid making a network request when the platform already has data that can be used by the player.
The `dataProvider` is a player `option` that takes a parameter function. This function must take an argument symbolizing the content object to be played, in the form of a `string`. Finally, this function must return a JSON object.
> [!TIP]
> How to use the `dataProvider` option
```javascript
const player = pillarbox('player', {
srgOptions: {
// defines the custom data provider
dataProvider: (data) => JSON.parse(data)
}
});
// A stringified object representing the mediaComposition
const mediaCompositionStringifiedObject = JSON.stringify({
// ...
});
// load the src
player.src({src: …
```

feat: add custom data handler

---

docs/api/tutorials/Player Tips and Tricks.md
src/middleware/srgssr.js
test/__mocks__/mainResource.json
test/middleware/srgssr.spec.js

Improves the `resource` property overriding mechanism when the `mediaData` 
object is provided to `player.src`. In certain scenarios, developers may want 
to add a subtitle track not provided by the media composition or even replace 
the media being played.
Although this use case is rare, it's essential to offer developers the 
flexibility to do so, ensuring a smoother developer experience.
> [!TIP]
> How to override a resource properties
```javascript
const player = pillarbox('player');
// overrides the URL and adds a blocking reason
player.src({
src: 'urn:bu:media:id', 
type:'srgssr/urn'
mediaData: {
url: 'https://fake-url.com/new-media.m3u8',
mimeType: 'application/x-mpegURL',
blockedSegments:[{
blockReason: "ENDDATE",
markIn: 5_000,
markOut: 60_000,
}]
}
});
```
> [!CAUTION]
> It's …

feat(srgssr-middleware): allow overriding of resource properties

---

docs/README.md
docs/api/index.md
package.json
rollup.config.js

Adds an 'exports' field in package.json to explicitly define entry points for ESM and CommonJS modules. This change ensures compatibility with different module systems and resolves module resolution issues in environments that rely on Node's resolution algorithm (like Vitest or Jest).
See: https://nodejs.org/api/esm.html#resolution-and-loading-algorithm
- Created a separate CommonJS builds for both core and non-core versions of pillarbox.
- Added a `main` field targeting the cjs build in the package.json for more flexibility.
- Added links to pillarbox-web-suite to the API documentation and README.
- Added a link to the personal accces token settings.

feat: add exports field to package.json

---

package.json

Introduces a new export under the `core` mapping to facilitate the use of the core functionalities of the `pillarbox` library. Integrators can now easily access the core bundle by importing it directly in their projects as shown below:
```javascript
// Using ES6 import syntax
import pillarbox from '@srgssr/pillarbox-web/core';
// Using CommonJS syntax
const pillarbox = require('@srgssr/pillarbox-web/core');
```
This update also includes an export to allow for straightforward mapping of all files included in the final bundle.
- Additional mappings in the export option of the `package.json`.

fix: add 'core' export and mapping for single files

---

docs/README.md
docs/api/index.md

Removes the `crossorigin="anonymous"` attribute from the <video-js> tag in the examples because we were experiencing issues with cross-origin media. This change ensures that integrators won't encounter the same error.

docs: remove crossorigin attribute from video-js tag in the examples

---

docs/README.md

The link to the `pillarbox-web-demo` was broken. It pointed to https://github.com/SRGSSR/pillarbox-demo instead of https://github.com/SRGSSR/pillarbox-web-demo.

docs: fix link to `pillarbox-web-demo` in `README.md`

---

.github/workflows/pre-release.yml
.github/workflows/release.yml
docs/README.md
docs/api/index.md
package.json

Resolves #260 by preparing the continuous integration for npm publishing.
- Updated GitHub Actions workflows to automate the publishing process to npm.
- Modified package.json files to ensure correct npm configuration.

fix: publish pillarbox-web to npm

---

src/lang/de.json
src/lang/en.json
src/lang/fr.json
src/lang/it.json
src/lang/rm.json

Resolves https://github.com/SRGSSR/pillarbox-web/issues/253 by adding a blocking reason that will enable editors to temporarily
block access to content if it needs to be edited an republished.
- add translation keys for error message

feat(lang): add journalistic blocking reason

---

src/trackers/PillarboxMonitoring.js

Resolves #277 by removing the `severity` property following the update of the 
monitoring specification.

fix(pillarbox-monitoring): remove severity property from error event

---

.github/workflows/release.yml

Adding the `registry-url` property to the `release` action should allow to select the tag to be promoted as the `latest` release from the github `releases` interface.
- add `registry-url` to `release.yml` file

chore(github-actions): add registry url to release action

---

src/trackers/SRGAnalytics.js

Resolves #265 by allowing the ADI team to measure videos played with the described audio track enabled.
- add a function to indicate whether the activated audio track is audio described or not
- add an event label named `media_audiodescription_on`

feat(analytics): track the type of audio track

---

README.md
docs/api/index.md
docs/api/jsdoc.json
docs/api/tutorials/Events.md
package.json

Use custom domain urls throughout the documentation.
- Updated all URLs to the demo page to point to `demo.pillarbox.ch`
- Updated all API documentation URLs to point to `web.pillarbox.ch/api`
- Updated all URLs to the theme editor to point to `editor.pillarbox.ch`
- Updated all URLs to the web suite demo to point to `plugins.pillarbox.ch`
- Updated all URLs to the marketing page to point to `www.pillarbox.ch`
- Updated all URLs to the Android documentation page to point to `android.pillarbox.ch`

fix: update urls for custom domain setup

---

src/trackers/PillarboxMonitoring.js
test/trackers/pillarbox-monitoring.spec.js

Fixes #283, by modifying the value of the error name sent, allowing clearer errors when consumed by other tools.
This modification supports the properties as defined by the [WHATWG](https://html.spec.whatwg.org/multipage/media.html#error-codes) as well as the two custom properties provided by video.js which are `MEDIA_ERR_CUSTOM` and `MEDIA_ERR_ENCRYPTED`.
- add a static method for setting the value of the error name
- add mock for `MediaError`

fix(pillarbox-monitoring): inconsistent error name value

---

src/middleware/srgssr.js
test/__mocks__/urn:geoblock:and:undefined:resourcelist.json
test/middleware/srgssr.spec.js

The latest IL update removes the `resourceList` object from geo-blocked `mediaComposition`. This change in behavior, even though the `resourceList` object is not a mandatory object, causes the player to return a non-compatible content error instead of a geoblock error.
- modify `getSrcMediaObj` so that `mediaData` contains an object containing `blockReason` and `imageUrl` if `mainResources` is empty.
- add test case

fix(srgssr-middleware): geoblocked mediaComposition without resourceList

---

scss/components/_progress.scss

Remove the play progress time tooltip when hovering the mouse to avoid overlapping with the mouse display time tooltip when they are close.
- modify the rule to disable the display of the time tooltip

feat(progress-control): remove play progress time tooltip

---

scss/components/_layout.scss

When the current time and media duration are displayed, it's easy for the user to visualize the time remaining to play. However, when the player is displayed in x-small or tiny, no time indication is shown.
- modify `_layout.scss` to display the remaining time when the player is displayed in x-small or tiny

feat(remaining-time-display): displays remaining time in x-small or tiny

---

build.es.js
docs/api/jsdoc.json
src/components/player.js
src/dataProvider/model/MediaComposition.js
src/dataProvider/services/DataProvider.js
src/middleware/srgssr.js
src/trackers/PillarboxMonitoring.js
src/trackers/SRGAnalytics.js
src/trackers/typedef.ts

Resolves #297 by exposing business classes, enabling their reuse across different projects.
- `build.es.js`, update to expose the following classes: `DataProvider`, `MediaComposition`, `PillarboxMonitoring`, and `SRGAnalytics`
- `jsdoc.json`, modify configuration to generate documentation for the exposed classes
- `PillarboxMonitoring`, add constructor documentation and created a type for constructor options
- `SRGAnalytics`, add constructor documentation and created a type for constructor options, update  links to the official documentation and reformatted documentation blocks for clarity

feat: make analytics, data source and monitoring classes public

---

src/dataProvider/model/MediaComposition.js

Exposes the (video) media container from the `mediaComposition`. This property will be exposed by the player through `mediaData` and will allow it to be used by the Google Cast receiver.
- expose the `mediaContainer` property via the `getMainResources` method.

feat(media-composition): add media container

---

scss/components/_layout.scss

When the player is resized to `vjs-layout-tiny` or `vjs-layout-x-small` while a live stream without DVR is being played, the progress bar appears even though it shouldn't.
https://github.com/user-attachments/assets/db38eb9e-f185-437a-a789-063d9046af25
- update display rules to ensure the progress bar is only shown for VOD and live streams with DVR.

fix(layout): progress bar displayed in tiny/x-small on live stream without DVR

---

src/trackers/PillarboxMonitoring.js
test/__mocks__/player-mock.js

Resolves #305 by retrieving the current audio and subtitle track languages from the player. Each time a `HEARTBEAT` or `ERROR` event occurs, the current audio and subtitle track will be added to the payload. This enhancement will help recreate the exact same context if needed for debugging or analysis.
- add a method to get the current audio track language
- add a method to get the current text track language
- add audio and text track language to the `HEARTBEAT` payload
- add audio and text track language to the `ERROR` payload
- test add mock for the audioTrack method

feat(pillarbox-monitoring): add subtitles and audio track language

---

src/lang/de.json
src/lang/en.json
src/lang/fr.json
src/lang/it.json
src/lang/rm.json

Resolves #311 by introducing a new blocking reason, `VPNPROXYDETECTED`, which will be displayed by the player whenever a VPN or proxy is detected by the backend. This will apply to content protected by DRM as well as certain live events.
- add translations for the new blocking reason

feat(lang): add VPN blocking reason

---

src/dataProvider/model/MediaComposition.js
test/__mocks__/urn:schedule:live:stream:chapters.json
test/dataProvider/model/MediaComposition.spec.js

Fixes #321, by removing chapters when the media type is not an episode. This follows the decision made during API discussion [#146](https://github.com/SRGSSR/pillarbox-documentation/issues/146#issuecomment-2883013095). Since Pillarbox lacks an automatic metadata update mechanism, removing chapters helps prevent confusion when a highlight is added during a live sports event.
Additionally, chapters in media types such as `EXTRACT`, `TRAILER`, and `CLIP` are considered a bug and should not be present.
- Remove chapters if the media is not an `EPISODE`
- Add a test case

fix(media-composition): remove chapters if the media is not type of EPISODE

---

.github/workflows/github-page.yml

Fixes #309 when the player version number being always one version behind when a new version of the player, and thus the GitHub page, is released.
- Runs the `Github Page` workflow only when the `Pre-release tag` has completed successfully. This should ensure that the version property in the package.json file is up to date before the GitHub page is published.

fix(github-actions): github page workflow

---

src/trackers/PillarboxMonitoring.js
test/trackers/pillarbox-monitoring.spec.js

In some cases, when a custom Tech is created, the return value of the function [`this.tech_[method]()`](https://github.com/videojs/video.js/blob/31f8d7ca102ba1a3bd62ef6b1dc8bd8f6e77719e/src/js/player.js#L2355
), where the value of `method` is `getVideoPlaybackQuality`, may be `undefined` for an undetermined reason during successive calls to the `getVideoPlaybackQuality` function. This causes an error to be thrown, preventing the monitoring data from being sent.
- add an empty object if `getVideoPlaybackQuality` is `undefined`
- update test case to try to induce error

fix(pillarbox-monitoring): undefined getVideoPlaybackQuality

---

README.md
docs/api/tutorials/ESM and import maps.md
docs/api/tutorials/Player Tips and Tricks.md

Resolves #333 by adding a tutorial based on the findings on issue #331.
- Added a tutorial on ESM resolutions through a CDN.
- Fixed a typo in an example on the tips and tricks tutorial.
- Added a link to the live UMD sample on the main README.
- Added a link to the collection of samples from the demo.

docs: adds a tutorial on how to integrate ecma scripts modules through a CDN

---

package-lock.json
package.json

Updating the `videojs-contrib-eme` package to the latest version fixes the playback issue on Safari for Macintosh devices.
This commit is marked as a fix and not as a chore in order to generate a new version of pillarbox.
It’s important to note that this commit does not fix the playback issue in Safari 
when switching from one DRM source to another on the same player instance. To fix 
that behavior, it will be necessary to upgrade to version v3.11.2. If that 
happens, the methods used to detect supported CDMs will no longer be available.
- update `videojs-contrib-eme` dependency

fix(npm): drm playback on safari
