package-lock.json, package.json
This PR adds additional configurations to the `package.json` file used to create a build, as well as various git-related information.
- add build target
- add `parcel` build script
- add `repository` property
- add `bugs` property
- update `package-lock` file
=> chore(package): add extra configuration

package-lock.json, package.json
This adds dev dependencies enabling semantic-release to perform various tasks.
- Update `package.json` file
- add `@semantic-release/changelog`
- add `@semantic-release/git`
- add `@semantic-release/github`
- add `@semantic-release/npm`
=> chore(semantic-release): add missing dev dependencies

.github/workflows/pre-release.yml, .github/workflows/quality.yml
Extracts `steps` from `pre-release` to create the `quality` workflow, in order to set up `status checks` on `pull-requests`.
- `pre-release`
- remove `linter` step
- remove `unit tests` step
- add `quality` workflow
=> chore(github-actions): add quality workflow

demo/index.html, demo/scss/index.scss, demo/src/index.js, package-lock.json, package.json, src/pillarbox.js, test/pillarbox.spec.js
This PR resolves #19 by adding to `Pillarbox` the same playback experience that `video.js` offers by default.
- adds `video.js` as a dependency
- `Pillarbox` inherits `video.js`
- `Pillarbox.VERSION` returns an object containing the version of the various modules used
- adds the player to the `demo`
- adds test coverage for `Pillarbox.VERSION`
=> feat(pillarbox): basic media playback

package-lock.json, package.json
Adds `buffer` as a development dependency, thus fixing github page generation.
- add `buffer` to `package.json` file
=> chore(npm): add buffer dev dependency

src/dataProvider/services/DataProvider.js
Inverting the condition makes the code easier to read.
=> refactor(dataDrovider): reverse the condition in getMediaCompositionByUrn

.github/workflows/coverage.yml, .github/workflows/quality.yml
Configure worflows for merge queues.
=> chore(github-actions): add merge queue

docs/CODE_OF_CONDUCT.md, docs/CONTRIBUTING.md, docs/README.md
Added a README.md draft, and a contribution guide based on the guides from pillarbox-apple.
=> docs: readme draft and contribution guide

demo/scss/examples.scss, demo/scss/index.scss
Simplifies some css styling.
- set `max-width` directely in `container`
- remove width from `example-btn`
- remove display flex from `examples` and `category`
- reduce paragraph specificity in `category`
=> chore(demo): update css rules

demo/src/example/examples.js
=> chore(examples): add media mime type

demo/index.html, demo/scss/content-tree.scss, demo/scss/dialog.scss, demo/scss/examples.scss, demo/scss/header.scss, demo/scss/index.scss, demo/scss/search.scss, demo/scss/spinner.scss, demo/src/content-lists/content-tree-page.js, demo/src/core/il-provider.js, demo/src/core/router.js, demo/src/core/spinner-component.js, demo/src/example/example-page.js, demo/src/header/header-component.js, demo/src/search/search-page.js, package-lock.json, package.json
Closes #81
Enhanced the overall user experience and visual appeal of the demo application.
- Added an icon and metadata to differentiate search results.
- Redisgned the buttons.
- Implemented a light/dark mode based on system preferences.
- Set a maximum width at the body level to ensure content remains consistent and avoids unexpected width changes.
- Addressed screen jerking when the scrollbar appears by applying the CSS rule `margin-left: calc(100vw - 100%);` to the HTML.
- Changed the look and feel of the  menu to enhance presentation.
- Added a fade-in animation when content appears, making transitions smoother.
- Removed autofill styling for inputs to provide a cleaner look.
- Reduced the size of the version in the title to optimize display on smaller screens.
- Removed `position: …
=> chore(demo): enhance ui with responsive design and improved aesthetics

demo/scss/search.scss
Displays an icon when the search screen is empty.
=> chore(search): add search icon

demo/src/content-lists/content-tree-root-sections.js
=> chore(demo): display bu alphabetically

demo/scss/index.scss
=> chore(demo): align button style to android and ios demos

demo/scss/search.scss, demo/src/search/search-page.js
Closes #80 and adds a few minor improvements.
- remove button overflow
- support for light theme
- typo in placeholder text
- use material icon instead of the SVG
=> chore(demo): search page improvements

demo/src/content-lists/content-tree-page.js, demo/src/core/router.js, demo/src/example/example-page.js, demo/src/search/search-page.js
Closes #99
- Introduces a "search as you type" with a debouncing function for the search page.
- Selecting a BU now also triggers a search reload automatically.
=> chore(demo): add search as you type

package.json
- update `package.json` to the add demo folder to `eslint`
=> chore(npm): add demo folder to linter

demo/src/search/search-page.js
Optimised the search experience to avoid  relaunching a search when the query value  hasn't changed.
=> chore(demo): optimize search to avoid relaunching on unchanged queries

src/middleware/srgssr.js
Modification of type descriptions in the various `SrgSsr` functions.
This allows better type hinting.
- updates the reference of types used
=> docs(srgssr-middleware): update jsdoc parameters

demo/scss/search.scss, demo/src/search/search-page.js
Closes #125
Added a button next tot he search input that allows to clear the results and said input box when clicked.
=> feat(demo): add clear search button

demo/scss/dialog.scss
Change the color of the dialog window close button to improve visibility.
- change color from dark to light
- remove extra empty lines
=> chore(demo): dialog close button visibility

demo/src/examples/examples.js
Add an HLS audio example that contains PTS rollover.
The player should be able to play from start to end without issues.
- add a new entry in `example.js`
=> chore(demo): add hls audio example

demo/src/player/player.js
Enabling smooth seeking makes interaction with the progress bar more responsive.
- `enableSmoothSeeking` option set to `true`
=> chore(demo): activates player smooth seeking

demo/src/examples/examples-page.js, demo/src/layout/header-component.js, demo/src/layout/header-component.scss, demo/src/lists/lists-page.js, demo/src/search/search-page.js, demo/src/settings/settings-page.js
Closes #154
- Extracted the title from the `<nav>` element and added un unorder list for the menu items.
- Replaced the `<div>` with `<section>` for all the pages.
=> chore(demo): use semantic tags

package.json
Updates the parcel target in charge of building the github page so that the `player.html` file is taken into account.
- modifies `package.json` `targets.github-page`
=> chore(npm): add player page to github-page

.github/workflows/pre-release.yml, .github/workflows/release.yml
Grant permissions to generate a new tag and finally authorize manual deployment of the NPM package in the GitHub registry
- add write permissions
=> chore(github-actions): enable npm package distribution

docs/api/tutorials/Known Issues.md
Resolves #208 by adding a tracking limitations section in the known issues article.
The new section describes the limitations of tracking multiple players in a single page scenario. A workaround section detailing how to disable tracking has been added, integrators are encouraged to track only one player at a time.
=> docs(analytics): add tracking limitations section to known issues

docs/api/jsdoc.json, package-lock.json, package.json, src/components/player.js, src/components/typedef.ts, src/dataProvider/model/MediaComposition.js, src/dataProvider/model/typedef.ts, src/middleware/srgssr.js, src/middleware/typedef.ts, src/utils/AkamaiTokenService.js, src/utils/Drm.js, src/utils/typedef.ts
Resolves #216 by enhancing type constraints and definitions.
This update provides improved type constraints and definitions, allowing developers to leverage stronger type checking. Integrators using typescript will also benefit from the stronger type checking.
For better control over types they are now defined in standalone typescript file instead of using jsdoc generation. Some types are still completed using jsdoc.
- Migrate existing jsdoc type definitions to typescript.
- Added types for the `MediaComposition` generated from the Swagger API definition.
- Defined types for all existing components.
- Added `better-docs` as a dev dependency to accurately parse TypeScript documentation for API site generation.
=> docs: update types and documentation

docs/api/tutorials/Default Options.md, docs/api/tutorials/Events.md
Adds a tutorial that introduces and explains custom events specific to SRG SSR media content, detailing how to handle events like `srgssr/blocked-segment`, `srgssr/chapter`, and `srgssr/interval` to enhance the playback experience, complete with practical examples and showcases.
- Updated the `Default Options` tutorial to include the recently introduced default value for the `fill` option.
=> docs: add custom event tutorial

package-lock.json, package.json
Update video.js to version [8.11.8](https://github.com/videojs/video.js/releases/tag/v8.11.8)
- update package.json and package-lock.json
=> chore(npm): update video.js to v8.11.8

package-lock.json, package.json
Update video.js to version 8.21.0 and videojs-contrib-eme to version 5.5.1
=> chore(npm): update to video.js and videojs-contrib-eme

.github/workflows/github-page.yml, .github/workflows/pre-release.yml, .github/workflows/preview.yml, .github/workflows/quality.yml, .github/workflows/release.yml
Updated the CI environment to use node.js 22, the current active LTS version.
=> ci: upgrade node version to 22 in ci workflow
